"""initial schema

Revision ID: ed08d932304b
Revises: 
Create Date: 2026-09-25 20:31:31.524011
"""
from alembic import op
import sqlalchemy as sa


revision = 'ed08d932304b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('delivery_targets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('transport', sa.String(length=20), nullable=False),
    sa.Column('config', sa.JSON(), nullable=False),
    sa.Column('recipient_party_id', sa.String(length=64), nullable=False),
    sa.Column('recipient_party_name', sa.String(length=200), nullable=False),
    sa.Column('test_mode', sa.Boolean(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=50), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('status', sa.Enum('queued', 'running', 'done', 'failed', name='jobstatus'), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('max_attempts', sa.Integer(), nullable=False),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('run_after', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_jobs_kind'), ['kind'], unique=False)
        batch_op.create_index(batch_op.f('ix_jobs_status'), ['status'], unique=False)

    op.create_table('royalty_statements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=100), nullable=False),
    sa.Column('period', sa.String(length=20), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('filename', sa.String(length=300), nullable=False),
    sa.Column('file_sha256', sa.String(length=64), nullable=False),
    sa.Column('gross_amount', sa.BigInteger(), nullable=False),
    sa.Column('matched_amount', sa.BigInteger(), nullable=False),
    sa.Column('line_count', sa.Integer(), nullable=False),
    sa.Column('unmatched_count', sa.Integer(), nullable=False),
    sa.Column('imported_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source', 'file_sha256')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=200), nullable=False),
    sa.Column('role', sa.Enum('artist', 'admin', name='role'), nullable=False),
    sa.Column('legal_name', sa.String(length=200), nullable=True),
    sa.Column('country', sa.String(length=2), nullable=True),
    sa.Column('stripe_account_id', sa.String(length=64), nullable=True),
    sa.Column('payouts_enabled', sa.Boolean(), nullable=False),
    sa.Column('email_verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('terms_accepted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('terms_version', sa.String(length=20), nullable=True),
    sa.Column('totp_secret', sa.String(length=64), nullable=True),
    sa.Column('totp_enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('stripe_account_id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    op.create_table('artists',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('spotify_artist_id', sa.String(length=64), nullable=True),
    sa.Column('apple_artist_id', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('artists', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_artists_owner_id'), ['owner_id'], unique=False)

    op.create_table('payouts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.BigInteger(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('status', sa.Enum('pending', 'paid', 'failed', name='payoutstatus'), nullable=False),
    sa.Column('stripe_transfer_id', sa.String(length=64), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('payouts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_payouts_user_id'), ['user_id'], unique=False)

    op.create_table('releases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('artist_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('version', sa.String(length=200), nullable=True),
    sa.Column('release_type', sa.Enum('Single', 'EP', 'Album', name='releasetype'), nullable=False),
    sa.Column('upc', sa.String(length=14), nullable=True),
    sa.Column('label_name', sa.String(length=200), nullable=False),
    sa.Column('genre', sa.String(length=100), nullable=False),
    sa.Column('subgenre', sa.String(length=100), nullable=True),
    sa.Column('language', sa.String(length=8), nullable=False),
    sa.Column('release_date', sa.Date(), nullable=False),
    sa.Column('original_release_date', sa.Date(), nullable=True),
    sa.Column('p_line_year', sa.Integer(), nullable=False),
    sa.Column('p_line', sa.String(length=300), nullable=False),
    sa.Column('c_line_year', sa.Integer(), nullable=False),
    sa.Column('c_line', sa.String(length=300), nullable=False),
    sa.Column('explicit', sa.Boolean(), nullable=False),
    sa.Column('territories', sa.String(length=1000), nullable=False),
    sa.Column('artwork_path', sa.String(length=500), nullable=True),
    sa.Column('status', sa.Enum('draft', 'in_review', 'approved', 'delivered', 'rejected', 'taken_down', name='releasestatus'), nullable=False),
    sa.Column('review_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['artist_id'], ['artists.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('upc')
    )
    with op.batch_alter_table('releases', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_releases_artist_id'), ['artist_id'], unique=False)

    op.create_table('deliveries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('release_id', sa.Integer(), nullable=False),
    sa.Column('target_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.Enum('insert', 'update', 'takedown', name='deliverykind'), nullable=False),
    sa.Column('batch_id', sa.String(length=40), nullable=False),
    sa.Column('message_id', sa.String(length=64), nullable=False),
    sa.Column('status', sa.Enum('queued', 'sent', 'acknowledged', 'failed', name='deliverystatus'), nullable=False),
    sa.Column('package_path', sa.String(length=500), nullable=True),
    sa.Column('remote_ref', sa.String(length=500), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['release_id'], ['releases.id'], ),
    sa.ForeignKeyConstraint(['target_id'], ['delivery_targets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('deliveries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_deliveries_release_id'), ['release_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_deliveries_target_id'), ['target_id'], unique=False)

    op.create_table('tracks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('release_id', sa.Integer(), nullable=False),
    sa.Column('track_number', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('version', sa.String(length=200), nullable=True),
    sa.Column('isrc', sa.String(length=12), nullable=True),
    sa.Column('iswc', sa.String(length=15), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('explicit', sa.Boolean(), nullable=False),
    sa.Column('audio_path', sa.String(length=500), nullable=True),
    sa.Column('audio_codec', sa.String(length=10), nullable=True),
    sa.Column('lyrics', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['release_id'], ['releases.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('release_id', 'track_number')
    )
    with op.batch_alter_table('tracks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tracks_isrc'), ['isrc'], unique=True)
        batch_op.create_index(batch_op.f('ix_tracks_release_id'), ['release_id'], unique=False)

    op.create_table('contributors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('track_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['track_id'], ['tracks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('contributors', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_contributors_track_id'), ['track_id'], unique=False)

    op.create_table('royalty_lines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('statement_id', sa.Integer(), nullable=False),
    sa.Column('track_id', sa.Integer(), nullable=True),
    sa.Column('isrc', sa.String(length=12), nullable=True),
    sa.Column('upc', sa.String(length=14), nullable=True),
    sa.Column('store', sa.String(length=100), nullable=True),
    sa.Column('territory', sa.String(length=10), nullable=True),
    sa.Column('usage_type', sa.String(length=50), nullable=True),
    sa.Column('quantity', sa.BigInteger(), nullable=False),
    sa.Column('amount', sa.BigInteger(), nullable=False),
    sa.Column('allocated', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['statement_id'], ['royalty_statements.id'], ),
    sa.ForeignKeyConstraint(['track_id'], ['tracks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('royalty_lines', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_royalty_lines_isrc'), ['isrc'], unique=False)
        batch_op.create_index(batch_op.f('ix_royalty_lines_statement_id'), ['statement_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_royalty_lines_track_id'), ['track_id'], unique=False)

    op.create_table('splits',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('track_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('percent', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['track_id'], ['tracks.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('splits', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_splits_email'), ['email'], unique=False)
        batch_op.create_index(batch_op.f('ix_splits_track_id'), ['track_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_splits_user_id'), ['user_id'], unique=False)

    op.create_table('ledger_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('email', sa.String(length=320), nullable=True),
    sa.Column('amount', sa.BigInteger(), nullable=False),
    sa.Column('kind', sa.Enum('royalty', 'commission', 'payout', 'payout_reversal', 'adjustment', name='ledgerkind'), nullable=False),
    sa.Column('royalty_line_id', sa.Integer(), nullable=True),
    sa.Column('payout_id', sa.Integer(), nullable=True),
    sa.Column('memo', sa.String(length=300), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['payout_id'], ['payouts.id'], ),
    sa.ForeignKeyConstraint(['royalty_line_id'], ['royalty_lines.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ledger_entries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ledger_entries_email'), ['email'], unique=False)
        batch_op.create_index(batch_op.f('ix_ledger_entries_payout_id'), ['payout_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ledger_entries_royalty_line_id'), ['royalty_line_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ledger_entries_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ledger_entries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ledger_entries_user_id'))
        batch_op.drop_index(batch_op.f('ix_ledger_entries_royalty_line_id'))
        batch_op.drop_index(batch_op.f('ix_ledger_entries_payout_id'))
        batch_op.drop_index(batch_op.f('ix_ledger_entries_email'))

    op.drop_table('ledger_entries')
    with op.batch_alter_table('splits', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_splits_user_id'))
        batch_op.drop_index(batch_op.f('ix_splits_track_id'))
        batch_op.drop_index(batch_op.f('ix_splits_email'))

    op.drop_table('splits')
    with op.batch_alter_table('royalty_lines', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_royalty_lines_track_id'))
        batch_op.drop_index(batch_op.f('ix_royalty_lines_statement_id'))
        batch_op.drop_index(batch_op.f('ix_royalty_lines_isrc'))

    op.drop_table('royalty_lines')
    with op.batch_alter_table('contributors', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_contributors_track_id'))

    op.drop_table('contributors')
    with op.batch_alter_table('tracks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tracks_release_id'))
        batch_op.drop_index(batch_op.f('ix_tracks_isrc'))

    op.drop_table('tracks')
    with op.batch_alter_table('deliveries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_deliveries_target_id'))
        batch_op.drop_index(batch_op.f('ix_deliveries_release_id'))

    op.drop_table('deliveries')
    with op.batch_alter_table('releases', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_releases_artist_id'))

    op.drop_table('releases')
    with op.batch_alter_table('payouts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_payouts_user_id'))

    op.drop_table('payouts')
    with op.batch_alter_table('artists', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_artists_owner_id'))

    op.drop_table('artists')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    op.drop_table('royalty_statements')
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_jobs_status'))
        batch_op.drop_index(batch_op.f('ix_jobs_kind'))

    op.drop_table('jobs')
    op.drop_table('delivery_targets')
    # ### end Alembic commands ###
